Repository palantir/golangci-lint-palantir, pull requests merged in 2025-09, with the labels that each got.

#2 Add safelogging check
  README.md
  godel/config/dist-plugin.yml
  pluginconfig/golangci.yml
Labels: autorelease

#23 Improvement: Add go-version-config to control go.mod version upgrades
  .palantir/go-version-config.v2.yml
Labels: merge when ready

#26 Update safelogging linter to v0.2.0
  godel/config/dist-plugin.yml
Labels: autorelease, merge when ready
